### ISSUE TITLE
建议加个一键清空当前文章的图床

### ISSUE THREAD

**Issue by SkiffBoy** [terwer/siyuan-plugin-picgo#121]
试了几个图床，发现就 Github 能用，但是其他的试过的图床信息依旧存在；
设置了多个图床，无法清理当前文章的图床链接；而且有重复的图片，虽然链接重传了，预览里面好几个重复的。

**Comment by terwer** [comment]
已升级重构，要验证下看看这个还有没有必要再次修改。
