### ISSUE TITLE
插件设置界面空白

### ISSUE THREAD

**Issue by syan2018** [terwer/siyuan-plugin-picgo#138]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/24589615/f932cffd-a08a-47c1-8b26-a458b3f9f882)
你好——想请教一下插件界面直接空白可能是因为什么呢？电脑上需要装什么依赖项吗？

**Comment by terwer** [comment]
更新到最新版本1.4.5呢？不需要其他依赖。

**Comment by syan2018** [comment]
卸载重装之后再重启siyuan竟然就好了！！！
