### ISSUE TITLE
插件打开空白

### ISSUE THREAD

**Issue by wyf115** [terwer/siyuan-plugin-picgo#164]
无论是设置还是正常打开都是空白。
控制台提示nB.isDesktopCapturerEnabled is not a function

**Comment by terwer** [comment]
思源笔记升级最新版本，插件升级到1.4.5.另外请提供更详细的错误信息。问题未复现

**Comment by zhangjunquan** [comment]
思源笔记版本
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/9114193/a1b801de-e943-4859-b642-89b3432ac8e4)

picgo插件版本
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/9114193/4930bd72-7817-485e-83c6-f9afcf024bb8)

打开后空白，没有提示信息
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/9114193/9260ad14-596f-4ee5-99e6-b3bcc0a10ad7)

**Comment by terwer** [comment]
2.18.0兼容问题，稍后修复。

**Comment by terwer** [comment]
> 重要提示：
> 
> 思源笔记 `2.10.8` 之前的版本请不要升级本插件，最高只能使用使用 `1.4.5` 版本。
> `2.10.8` 之后的版本可升级到最新版 PicGO 插件到 `1.5.0+` 。

**Comment by Achuan-2** [comment]
更新之后依然显示空白
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/60436214/b0f08ffa-0fc9-4213-a660-74048e1c2feb)
