### ISSUE TITLE
图片重复问题

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-picgo#173]
发现图片放在列表块里就会重复三张
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/60436214/0346e1e3-c529-4a43-81b9-259ba5bbb16f)
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/60436214/25afc2a0-ac0f-4153-bc0f-98a5b5a9e9bc)

应该是思源本身的块结构问题导致的

**Comment by terwer** [comment]
看看新版本还有没有这个问题，有问题可再次提出。
