### ISSUE TITLE
请问有考虑支持lankong插件吗？

### ISSUE THREAD

**Issue by waxnx** [terwer/siyuan-plugin-picgo#197]
如题，请问有没有考虑支持lankong插件吗？

**Comment by wanyunr** [comment]
同求

**Comment by yalidabuda** [comment]
附议

**Comment by terwer** [comment]
已支持，可升级 1.11.0，感谢 https://github.com/lsky-org/lsky-pro/issues/256 提供的部署方案。

**Comment by yalidabuda** [comment]
> 已支持，可升级 1.11.0，感谢 [lsky-org/lsky-pro#256](https://github.com/lsky-org/lsky-pro/issues/256) 提供的部署方案。

牛批🐂🍺
