### ISSUE TITLE
强烈建议适配一下兰空图床

### ISSUE THREAD

**Issue by codeses** [terwer/siyuan-plugin-picgo#21]
图床功能还挺重要的，包括加水印  裁剪  图片管理的

**Comment by SkysCrystal** [comment]
+1 希望适配[兰空图床](https://github.com/hellodk34/picgo-plugin-lankong)插件

**Comment by laozhangge** [comment]
+1 希望适配[兰空图床]

**Comment by dengxuezhao** [comment]
＋1 希望适配

**Comment by UPToZ-Core** [comment]
+1 希望能够适配一下兰空图床

**Comment by yalidabuda** [comment]
+1

**Comment by terwer** [comment]
已支持，可升级 1.11.0，感谢 https://github.com/lsky-org/lsky-pro/issues/256 提供的部署方案。
