### ISSUE TITLE
优化图片上传选择

### ISSUE THREAD

**Issue by BonjourL** [terwer/siyuan-plugin-picgo#211]
看到了作者的使用须知,关于第2点，能不能选择是直接替换原始图片，还是存储本地图片与图床图片的映射信息。

> 使用须知：
1、此处上传的图片不会自动插入文档中，请手动点击按钮复制链接，然后 Ctrl+V 粘贴到文档中。
2、对于文档当中原本已经存在的本地图片，点击上传之后不会直接替换原始图片，只会存储本地图片与图床图片的映射信息，需要在发布文章时手动勾选【使用图床】才会进行临时链接替换，请知悉。 这样做是为了不破坏其他地方对文档图片的处理。当然，您也可以手动复制图床链接，然后删除原图片，替换为图床图片。
3、该图片列表仅展示此文档包含的图片。

**Comment by terwer** [comment]
之前不替换是为了害怕破坏 dom。如果需求大，可以支持替换。

**Comment by BonjourL** [comment]
> 之前不替换是为了破坏dom。如果需求大，可以支持替换。

经常会有这样的场景

**Comment by terwer** [comment]
直接粘贴上传会有延时 10 秒（默认，可配置），然后自动替换链接。请更新 1.6.0+.注意：其他模式不支持，仅支持粘贴复制到思源笔记编辑器的情景。
