### ISSUE TITLE
docker版本不兼容

### ISSUE THREAD

**Issue by TRAVISZHAN** [terwer/siyuan-plugin-picgo#214]
Picgo插件版本v1.5.1，思源笔记版本v2.10.14。插件下载后提示版本不兼容，无法使用

**Comment by terwer** [comment]
非常抱歉，目前不支持 docker。仅支持 PC 客户端。

**Comment by terwer** [comment]
已经支持 docker，需要更新1.6.0+，还需要设置 cors 跨域代理，有问题可咨询 youweics@163.com

**Comment by hausen1012** [comment]
> 已经支持 docker，需要更新1.6.0+，还需要设置 cors 跨域代理，有问题可咨询 [youweics@163.com](mailto:youweics@163.com)

你好，这样配置还是提示 您必须配置CORS代理，

<img width="1265" height="186" alt="Image" src="https://github.com/user-attachments/assets/cd22b42c-99c9-4e14-9521-9785812b4840" />
