### ISSUE TITLE
图床复制链接能否提供html格式

### ISSUE THREAD

**Issue by Benjamin-Watson0** [terwer/siyuan-plugin-picgo#218]
是这样，目前我想把文章里的图片批量上传至图床。然后用在发布文章插件中源码预览模式中复制出来。这样我就得到了一篇纯字符的文章，方便我后续操作。
我会把文字复制到一个叫“anki"的软件，它的图床只能用html格式的。
图床复制链接能否提供html格式，其实主要是想要发布文章插件中，源码预览模式下的MD正文中的图床链接是html格式的（我只是想要图床是html格式的，复制html正文不是我想要的）。
谢谢帮助

**Comment by terwer** [comment]
已支持 html md 原始连诶等复制，请更新 1.6.0+
