### ISSUE TITLE
发布设置问题

### ISSUE THREAD

**Issue by leoleelxh** [terwer/siyuan-plugin-picgo#226]
求教：
插件有一段说明：

**对于文档当中原本已经存在的本地图片，点击上传之后不会直接替换原始图片，只会存储本地图片与图床图片的映射信息，需要在发布文章时手动勾选【使用图床】才会进行临时链接替换**

在哪里选择发布设置啊？

**Comment by terwer** [comment]
文档落后了，目前没有选项，安装了 picgo 插件会自动使用。不想使用就卸载 picgo 插件。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月29日 12:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-picgo] 发布设置问题 (Issue #226) |

求教：
插件有一段说明：

对于文档当中原本已经存在的本地图片，点击上传之后不会直接替换原始图片，只会存储本地图片与图床图片的映射信息，需要在发布文章时手动勾选【使用图床】才会进行临时链接替换

在哪里选择发布设置啊？

**Comment by terwer** [comment]
新版本发布工具有图床服务选择了。
