### ISSUE TITLE
一键重新上传

### ISSUE THREAD

**Issue by Evander-Liam** [terwer/siyuan-plugin-picgo#344]
若之前图片已经上传过，那么此时图片已经建立映射，虽然有重新上传这个按键，但却没有一键重新上传，一个个点就太麻烦了。
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/101777683/898e48a2-52b1-4514-a0c8-b14b07aa6303)

比如我想换个图床或原本图床已经不在沿用的时候，就有这个需求。

希望增加“一键重新上传”功能。

**Comment by terwer** [comment]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/be9fc044-5e59-4402-a7b3-3fb47e1b553b)
文档标题菜单->属性->自定义属性，删除 picgo-file-map-key 这个属性即可。

**Comment by Evander-Liam** [comment]
好的，已解决。
