### ISSUE TITLE
外置picgo粘贴图片报错

### ISSUE THREAD

**Issue by Paxton-PKJ** [terwer/siyuan-plugin-picgo#354]
思源版本: 3.0.7
插件版本: 1.9.0

使用外部picgo server时，截图后粘贴图片出现报错：
`剪贴板图片上传失败，错误原因：Error: blob is not supported via external picgo api`

开发者工具出现报错：
`plugin:siyuan-plugin-picgo:8 [zhi-siyuan-picgo] [2024-04-04 14:08:36] [ERROR] [picgo-post-api] move D:\siyuan_workspace\data\plugins\siyuan-plugin-picgo\libs\setup to C:\Users\52563\.universal-picgo\libs\setup failed: Error: EXDEV: cross-device link not permitted, rename 'D:\siyuan_workspace\data\plugins\siyuan-plugin-picgo\libs\setup' -> 'C:\Users\52563\.universal-picgo\libs\setup'`

复制本地文件粘贴图片无反应

内置picgo使用正常

**Comment by haer2829** [comment]
我也遇到这个问题

**Comment by terwer** [comment]
剪切板板可直接用这个按钮，其他情形建议使用选择上传或者拖拽上传。

![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/299344b4-45c7-4d32-84b9-450ffeafcbc4)
