### ISSUE TITLE
本地图片上传图床后，无法替换链接自动转换成在线图片

### ISSUE THREAD

**Issue by L0223** [terwer/siyuan-plugin-picgo#359]
![20240406183013](https://github.com/terwer/siyuan-plugin-picgo/assets/53463101/ec9de83b-0184-49f3-b0c6-633491c9bdd0)
粘贴板直接粘贴进来的图片可以自动上传至图传并替换成url链接，本地添加的图片就不行，即使手动上传至图床。这是为什么咧？

**Comment by terwer** [comment]
目前仅支持粘贴板直接粘贴进来的图片可以自动上传，1.10.0 考虑加一个菜单手动上传并替换链接。

**Comment by terwer** [comment]
fixed in `1.10.0`

核心变更如下：🎉

1、延迟改成了轮询，体验好了很多。一般每隔 2 秒轮询一次，正常情况 1-2 次都能成功。5 次之后失败，可配置。
2、直接在插件弹窗上传也可以支持链接替换了。现在全凭用户自己配置。希望这样能消除旧版本的一些误解。
3、如果想手动，可以先关闭剪切板自动上传，然后打开弹窗，点击一键上传，现在弹窗里面点击一键上传也能够替换啦（前提是笔记已经存在的图片）🎉。这样是很安全的，因为没有轮询😊，`1.10.0` 可用。
