### ISSUE TITLE
希望增加对piclist的远程调用

### ISSUE THREAD

**Issue by hzj629206** [terwer/siyuan-plugin-picgo#360]
piclist 支持 Docker 部署在服务器端，当前插件只支持本地安装的 picgo 或 piclist。
远程调用应该是要把图片数据本身发送过去，本地调用是把图片的路径发送过去的。

参考Obsidian的 Image auto upload 插件：https://github.com/renmu123/obsidian-image-auto-upload-plugin

piclist 支持更多的内置图床，在桌面和移动端都可以较好地满足需求。

**Comment by UPToZ-Core** [comment]
> piclist 支持 Docker 部署在服务器端，当前插件只支持本地安装的 picgo 或 piclist。 远程调用应该是要把图片数据本身发送过去，本地调用是把图片的路径发送过去的。
> 
> 参考Obsidian的 Image auto upload 插件：https://github.com/renmu123/obsidian-image-auto-upload-plugin
> 
> piclist 支持更多的内置图床，在桌面和移动端都可以较好地满足需求。

我使用本地的Piclist出现这种错误Error: Blob does not support external picgo API v3.0.9

**Comment by hzj629206** [comment]
Hi @UPToZ-Core,

Docker 部署的 PicList 是 [PicList-Go](https://github.com/Kuingsmile/PicList-Core).
本地安装的 PicList 是 https://github.com/Kuingsmile/PicList.

二者是有区别的。[obsidian-image-auto-upload-plugin](https://github.com/renmu123/obsidian-image-auto-upload-plugin) 是提供一个选项表示远程与否。

**Comment by UPToZ-Core** [comment]
> Hi @UPToZ-Core,
> 
> Docker 部署的 PicList 是 [PicList-Core](https://github.com/Kuingsmile/PicList-Core). 本地安装的 PicList 是 https://github.com/Kuingsmile/PicList.
> 
> 二者是有区别的。[obsidian-image-auto-upload-plugin](https://github.com/renmu123/obsidian-image-auto-upload-plugin) 是提供一个选项表示远程与否。PicList-Core 不支持`/delete` API.

我主要是本地使用，所以我安装的是本地的然后打开server服务

**Comment by terwer** [comment]
剪切板板可直接用这个按钮，其他情形建议使用选择上传或者拖拽上传。已支持外部 picgo 的 picgo-server，应该能兼容 piclist。

![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/299344b4-45c7-4d32-84b9-450ffeafcbc4)

**Comment by terwer** [comment]
需要升级  1.10.1

**Comment by UPToZ-Core** [comment]
升级了1.10.1依然报错Error: cannot not find valid image v3.0.10

**Comment by terwer** [comment]
你是通过拖拽还是选择图片？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月23日 11:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [terwer/siyuan-plugin-picgo] 希望增加对piclist的远程调用 (Issue #360) |

升级了1.10.1依然报错Error: cannot not find valid image v3.0.10

**Comment by UPToZ-Core** [comment]
> 你是通过拖拽还是选择图片？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年04月23日 11:35 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>、State ***@***.***> | | 主题 | Re: [terwer/siyuan-plugin-picgo] 希望增加对piclist的远程调用 (Issue #360) | 升级了1.10.1依然报错Error: cannot not find valid image v3.0.10 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

通过直接粘贴在思源笔记内自动上传

**Comment by UPToZ-Core** [comment]
使用粘贴板上传就报错-》操作失败=>Error: cannot not find valid image

**Comment by terwer** [comment]
我好像知道问题了，下版本修复。plist非剪切板应该可以用的。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月23日 11:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [terwer/siyuan-plugin-picgo] 希望增加对piclist的远程调用 (Issue #360) |

使用粘贴板上传就报错-》操作失败=>Error: cannot not find valid image

**Comment by UPToZ-Core** [comment]
> 我好像知道问题了，下版本修复。plist非剪切板应该可以用的。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年04月23日 11:42 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>、State ***@***.***> | | 主题 | Re: [terwer/siyuan-plugin-picgo] 希望增加对piclist的远程调用 (Issue #360) | 使用粘贴板上传就报错-》操作失败=>Error: cannot not find valid image — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

是的，使用一键上传，或者选择一张张图片上传是可以的

**Comment by KingStoning** [comment]
> > piclist 支持 Docker 部署在服务器端，当前插件只支持本地安装的 picgo 或 piclist。 远程调用应该是要把图片数据本身发送过去，本地调用是把图片的路径发送过去的。
> > 参考Obsidian的 Image auto upload 插件：https://github.com/renmu123/obsidian-image-auto-upload-plugin
> > piclist 支持更多的内置图床，在桌面和移动端都可以较好地满足需求。
> 
> 我使用本地的Piclist出现这种错误Error: Blob does not support external picgo API v3.0.9

你现在本地调用还可以使用吗？
我本地安装了piclist，打开了server，在插件里面选择了picgo（app）填上了http://[127.0.0.1:36677/upload](http://127.0.0.1:36677/upload) 但是调用失败

操作失败=>Error: 调用HTTP上传到PicGO失败，请检查配置=>undefined
操作失败=>Error: invalid ID argument
