### ISSUE TITLE
minio如何对接插件作为图床

### ISSUE THREAD

**Issue by flyingnight** [terwer/siyuan-plugin-picgo#363]
您好，我自己部署的minio如何对接插件作为图床？

**Comment by terwer** [comment]
下版本我测试一下，新版还没来记得进行兼容测试，敬请期待


| |
youweics
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月8日 12:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-picgo] minio如何对接插件作为图床 (Issue #363) |

您好，我自己部署的minio如何对接插件作为图床？

**Comment by terwer** [comment]
新版本 `1.10.0` 加了 s3，可以按照 s3 来配置。

![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/9681217d-5659-4796-ba79-b5d384c88c25)

![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/763448f0-9e87-4468-8968-217643790659)
