### ISSUE TITLE
图床的图片列表中重复出现好几次图片

### ISSUE THREAD

**Issue by sumruler** [terwer/siyuan-plugin-picgo#364]
本地图片点击一键上传以后，貌似并没有替换成外链
![Clip_2024-04-08_19-25-28](https://github.com/terwer/siyuan-plugin-picgo/assets/56953545/3fef2567-0a04-4f82-879d-3c2524975bc2)
图片di地址仍然显示本地地址
另外图床图片列表每次点击一键上传好像就会再上传一遍，然后列表里面就会重复出现多次图片。
![Clip_2024-04-08_19-26-46](https://github.com/terwer/siyuan-plugin-picgo/assets/56953545/4672f1af-7eb4-4c1c-ac84-ff112a51cebc)

**Comment by terwer** [comment]
新版本看看还有没有这个问题，有问题再提出来。

**Comment by sumruler** [comment]
新版本已经正常，没有出现这个问题了

**Comment by UPToZ-Core** [comment]
为啥我新版本还是会出现这种问题呢

**Comment by UPToZ-Core** [comment]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/73866989/eb2ce34f-242f-475d-9030-da3c2f8a394c)
出现多次相同图片

**Comment by shuojie819** [comment]
最新版：v1.10.2，还是会出现重复问题，这导致这个插件几乎不可用……
![图床 BUG](https://github.com/terwer/siyuan-plugin-picgo/assets/72399630/8414ad09-9f9a-41db-94ec-17a4da08f9ff)
