### ISSUE TITLE
本地图片在替换外链图片过程中，如果调整了图片大小，替换完成后会恢复原来调整之前的大小

### ISSUE THREAD

**Issue by sumruler** [terwer/siyuan-plugin-picgo#366]
本地图片在替换外链图片过程中，如果调整了图片大小，替换完成后会恢复原来调整之前的大小，这个体验不太好，因为替换过程需要几秒的时间，比较漫长，这个过程中不能调整大小，要到上传之后再回来调整，非常影响写作的沉浸式体验

**Comment by terwer** [comment]
新版本使用了轮询，不需要一直等待，一般的图片 1-2s 就已经能完成替换。另外，我也打算在替换之前检测属性，如果有修改看看能不能合并。

**Comment by terwer** [comment]
已修复

**Comment by myg321** [comment]
> 新版本使用了轮询，不需要一直等待，一般的图片 1-2s 就已经能完成替换。另外，我也打算在替换之前检测属性，如果有修改看看能不能合并。

作者你好！！我已开启“替换本地链接”选项，但是在“一键替换”并提示成功之后，当前文档内图片链接还是本地路径链接而非URL图床链接，请问下替换成网络图床链接这个功能，有什么使用步骤或者条件吗？？是不是要在提示替换成功之后等待一会儿呢？
