### ISSUE TITLE
提供开关 「粘贴到思源自动上传」

### ISSUE THREAD

**Issue by terwer** [terwer/siyuan-plugin-picgo#379]
提供开关 「粘贴到思源自动上传」，名字也可以叫 「剪切板自动上传」，哪个好？

拆解成两个选项：自动上传，替换本地连接

**Comment by sumruler** [comment]
第一个好，比较好理解些

**Comment by shuojie819** [comment]
作者大大可以参考一下obsidian的 “Image auto upload Plugin” 插件，感觉提不错的。
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/72399630/801f615f-de71-41de-92e6-37c41fdb0ce2)
他可以批量上传并替换原文中的链接、还可以上传网络图片……
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/72399630/14c3a622-d36b-4993-bc2b-9b9b81a95de4)

**Comment by terwer** [comment]
fixed in `1.10.0`
