### ISSUE TITLE
Error: Blob does not support external picgo API v3.0.9

### ISSUE THREAD

**Issue by UPToZ-Core** [terwer/siyuan-plugin-picgo#380]
在PC端安装了piclist，然后粘贴图片会出现“Error: Blob does not support external picgo API v3.0.9”的错误。
但是在插件内上传图片是正常的，另外希望增加一个配置是否粘贴图片自动上传的功能。因为我不能保证我粘贴进文章的图片都是需要上传到图床的。

**Comment by terwer** [comment]
粘贴图片自动上传选项已在 1.10.0 增加。另一个错误将在 `1.10.1` 修复 。

**Comment by terwer** [comment]
剪切板板可直接用这个按钮，其他情形建议使用选择上传或者拖拽上传。

![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/299344b4-45c7-4d32-84b9-450ffeafcbc4)
