### ISSUE TITLE
关于上传文件大小限制

### ISSUE THREAD

**Issue by zbs4017** [terwer/siyuan-plugin-picgo#404]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/41728484/a78c78ae-c198-44b7-86cd-9c5315983888)
我看到这里有大小的限制，请问这个限制是可以去除的吗？

**Comment by terwer** [comment]
这个只是个建议，实际逻辑并没有限制，新版本 `1.10.1` 已经去掉这个提示。
单个限制为 5 是做了限制的。
