### ISSUE TITLE
新版本的bug

### ISSUE THREAD

**Issue by zbs4017** [terwer/siyuan-plugin-picgo#406]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/41728484/f8a0f089-3362-4308-a8ca-f5bb8edf4ad1)
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/41728484/43027277-72ec-47f7-adc4-aa3cb5f0cdaa)
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/41728484/fb5368aa-b7ad-480e-b2eb-825d6c072ed4)

配置七牛云的时候，如果网址后缀为空，配置中会默认null，null会添加到网址的路径，最终导致出错

**Comment by terwer** [comment]
已修复，请升级 `1.10.1`
