### ISSUE TITLE
对于文档当中原本已经存在的本地图片，点击上传之后不会直接替换原始图片，可以进行配置选择

### ISSUE THREAD

**Issue by BonjourL** [terwer/siyuan-plugin-picgo#50]
对于文档当中原本已经存在的本地图片，点击上传之后不会直接替换原始图片，可以进行配置选择，选择是否替换

**Comment by xuguangjian** [comment]
这个不容易做吧，即使是已经做得不错的typora，也不会直接替换，只会重复上传

**Comment by hzj629206** [comment]
> 这个不容易做吧，即使是已经做得不错的typora，也不会直接替换，只会重复上传

不替换的话，重复上传的意义是什么呢？

**Comment by terwer** [comment]
新版本支持粘贴模式替换链接了。

**Comment by hzj629206** [comment]
@terwer Sorry 问一下，重复上传这个功能的设计意图是什么样的呢？即什么情况下应该使用这个重复上传？

是不是说重复上传往粘贴板里写入新的 url，然后人工去替换呢？

**Comment by hzj629206** [comment]
把远程链接对应的图片上传到图床，但是并不更新当前文档的链接为图床链接。

就是单纯地上传到图床一般的用途是什么样的呢？

**Comment by terwer** [comment]
这个其实是之前笔记 API 不支持没办法实现替换的一个妥协，目前已经支持替换了，我这在开发替换功能。
但是为了老用户的习惯会保留一个配置项。

![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/9a2e67e1-41be-4125-b4dc-ca31545e150c)


到时候可在 `1.10.0` 体验。

**Comment by hzj629206** [comment]
了解了，感谢 @terwer 。
