### ISSUE TITLE
七牛云上传不支持https

### ISSUE THREAD

**Issue by mhlywxl** [terwer/siyuan-plugin-picgo#504]
思源笔记地址用的https地址的情况下，代码里面七牛云上传固定写的http的上传，麻烦适配下支持https的
![Snipaste_2024-06-23_16-33-03](https://github.com/terwer/siyuan-plugin-picgo/assets/8207774/a4d73161-cb82-4612-af3c-d5f342a5952c)
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/8207774/c6685cb9-d45e-4f62-aecd-9cafb8773321)

顺便请教下，思源支持测试离线的插件包吗，可以的话我都想自己改代码测试通过后再提个pr过来

**Comment by terwer** [comment]
fixed in `v1.12.0`
