### ISSUE TITLE
请问能不能增加一个单个文档上传所有本地图片的功能呢？

### ISSUE THREAD

**Issue by Kikkwa** [terwer/siyuan-plugin-picgo#620]
我导入了网络上的 MD 文档，但是为了图床的稳定可靠。想要把所有的图片都换成自己的图床，用思源自带功能可以把网络图片方便的下载到本地，用插件可以把所有的图片上传到云端上面么？

**Comment by terwer** [comment]
![image](https://github.com/user-attachments/assets/53194696-b1a6-4d61-b67a-38c34fa1768d)

这里早已实现了这个功能。
