### ISSUE TITLE
右键上传图片到图床会出现替换本体图片失败的情况

### ISSUE THREAD

**Issue by KangLuan-VgZeFa** [terwer/siyuan-plugin-picgo#637]
![problem](https://github.com/user-attachments/assets/78c16b34-85c0-4b4a-bd2b-241fd81b2b16)
虽然在上传之后显示已经替换成了图床链接，但是只要重新打开思源就会发现还是本体图片。

**Comment by terwer** [comment]
需要同步一下或者创建索引。这种不是插件本身的问题。
