### ISSUE TITLE
同时上传多张图片的时候，只有最后三张本地图片可以替换成图床链接，但是希望所有的图片可以被替换成图床链接

### ISSUE THREAD

**Issue by C107-9** [terwer/siyuan-plugin-picgo#638]
之前是只有最后一张本地图片可以替换成图床链接，现在是只有最后三张本地图片替换成图床链接

**Comment by congSjwbsz** [comment]
就是，只有最后一张本地图片可以替换成图床链接，人家弄配置弄了那么辛苦，到最后发现并没有达到效果，麻了

**Comment by terwer** [comment]
只会替换 assets 这种本地图片。如果图片本身是链接，会忽略。

**Comment by terwer** [comment]
或许可以新增图床白名单功能。设置了之后，白名单之外的链接均强制上传。

**Comment by congSjwbsz** [comment]
没有呀，都是本地的

https://github.com/user-attachments/assets/aefda6b6-15be-4ff4-9836-e53e2579de06

**Comment by C107-9** [comment]
全都是本地assets图片，一键上传我上次测试是只有3张图片替换了链接，很多人都在反馈这个问题[#616](https://github.com/terwer/siyuan-plugin-picgo/issues/616)

**Comment by terwer** [comment]
我大概知道啥问题了，粘贴之后块生成，和图床上传是并行的，这就存在一个时序问题。
你们的问题之所随机，是因为如果块生成速度比较快，那么应该能替换成功。如果块生成岁读较慢，那么图片完成后查不到这个块替换失败，当块生产之后有没有做重试。
我尝试重构一下批量上传这块的逻辑吧。估计还得启用轮询去做。

**Comment by terwer** [comment]
fixed in `v1.12.0`
