### ISSUE TITLE
图床显示多张重复的图片，并且上传到图床时，它也重复的进行上传多张重复图片

### ISSUE THREAD

**Issue by KSMLC** [terwer/siyuan-plugin-picgo#639]
原文章我已导出，麻烦你导入进去后查看是否出现这种情况：https://ksmlc.lanzouw.com/iUCCH2g8eg1i
![](https://alist.ksmlc.cn/d/Private/Cloudreve/%E5%9B%BE%E7%89%87/%E5%9B%BE%E5%BA%8A/202411251651324.png)

**Comment by terwer** [comment]
感谢反馈，我排查一下。

**Comment by terwer** [comment]
`v1.12.0` 再试试看还有没有问题。

**Comment by KSMLC** [comment]
> `v1.12.0`再试试看还有没有问题。

![image](https://github.com/user-attachments/assets/a963f516-ecd5-47d0-9901-63c98f8bb08d)

v1.12.0依旧存在重复图片，而且我只点击了一次【上传本地图片到图床】，它却会把另一张重复的也给上传上去了
![image](https://github.com/user-attachments/assets/4d0c9af9-8cd8-4a88-83ce-5fde3f3c8cbb)
这是输出的日志
[127.0.0.1-1732868870900.log](https://github.com/user-attachments/files/17956401/127.0.0.1-1732868870900.log)

**Comment by terwer** [comment]
感谢反馈，我排查下。接下来的小版本修复。
关注 `v1.12.1`

**Comment by terwer** [comment]
fixed in `v1.12.1`
