### ISSUE TITLE
图标不显示，无法使用

### ISSUE THREAD

**Issue by xuguangjian** [terwer/siyuan-plugin-picgo#87]
安装完最新picgo插件，连图标都不显示了，
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/66892415/d6d8c4cd-6a67-492c-82a4-892ac5fbf043)
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/66892415/a4424402-67a8-4d5a-a4b4-29b6040dcb24)

**Comment by terwer** [comment]
抱歉，最近迭代频繁，测试未充分。已修复，请稍后升级 1.4.5

**Comment by terwer** [comment]
如果1.4.5升级之后还是异常，请 **卸载之后再重新下载** ，不要覆盖更新。

**Comment by xuguangjian** [comment]
已经能正常使用了。



| |
许广健
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月14日 17:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [terwer/siyuan-plugin-picgo] 图标不显示，无法使用 (Issue #87) |

如果1.4.5升级之后还是异常，请 卸载之后再重新下载 ，不要覆盖更新。
