### ISSUE TITLE
显示  < ％ · injectScript ％ >

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-picgo#93]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/60436214/fec92ff3-5f95-4347-bd2e-629f49e4b0bb)

**Comment by terwer** [comment]
抱歉，最近迭代频繁，测试未充分。已修复，请稍后升级 1.4.5

**Comment by terwer** [comment]
如果1.4.5升级之后还是异常，请 **卸载之后再重新下载** ，不要覆盖更新。
