### ISSUE TITLE
上传替换链接

### ISSUE THREAD

**Issue by xuguangjian** [terwer/siyuan-plugin-picgo#94]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/66892415/efc9b2ce-9504-45c6-a951-e9c3a6dd9c7f)
作者有没有想过做成typora的上传样式，右键点击上传，成功之后把原有图片以链接显示，这样会很省空间，而且如果要发布的话就不用手动一张张替换了

**Comment by xuguangjian** [comment]
👍🏻

**Comment by xuguangjian** [comment]
作者有没有用过obsidian，里面有个插件是粘贴图片自动用picgo上传，不过也有问题，不能自己选择，只能粘贴的时候自动上传一次，也不能更改，只是建议，反正作者的插件很好用，即使是不更新新功能也会使用，只要是稳定就好了
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/66892415/daeaa35c-afcb-4f4d-9294-eaabaa192f8f)
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/66892415/f26096a5-3f24-440d-9db2-042b6bbc12d2)

**Comment by terwer** [comment]
新版本支持粘贴模式自动上传了。
